### ISSUE TITLE
create personas for ortelius customers

### ISSUE THREAD

**Issue by Neetuj** [ortelius/ortelius#137]

**Comment by Neetuj** [comment]
@TracyRagan @sbtaylor15  @markyjackson-taulia   can you point me to few different types of users and buyers to start creating these personas?

**Comment by TracyRagan** [comment]
Great question.

**Cloud Architects** are interested in designing around microservices, how to mange them, track them and create reuse. 
**SREs** are the ones that must answer the questions and need the visibility maps in order to make confident decisions about pushing a service to a cluster.
  **DevOps engineers** are facing the shifting pipeline. They are looking for ways to evolve the Pipeline to support microservices, which Ortelius helps. 
**Microservice Developers** often don't see or care about the bigger picture, but they do want to know who is consuming their services and who the impact in an update.  They also are looking for ways to 'publish' their service so in can be reused.  Their success is tied to the success of the services they create.
**Testing teams** need help understanding what they need to test. A new microservice may impact multiple applications, the want to know which applications need to be retested.

From a Industry perspective:

Global Service Companies like IBM, Unisys, VMWare - they are looking at building a library of resuable microservices that can be shared across teams for delivering custom code to their customers.  This is a particular suite spot for early adopters of Ortelius because of its Domain Driven Design Catalog and sharing capability. 

Highly Audited - FinTech, Insurance, Medical - these industries should be a target for Ortelius.  Ortelius gives them the audits around microservices that are otherwise difficult to manage. Release Automation has been purchased by these industries, but not well adopted. That is because the release automation solutions are often an "all or nothing" approach meaning every team must comply.  That is a heavy and long road. And with microservices, the traditional release automation solutions are outdated. 

Telcom - This is an interesting segment because they must adopt a Kubernetes architecture to handle the auto scaling. Some have already gone down the microservices road and are facing some pretty big hair balls.  We should be keeping this group in mind as end users that can give us insights into their struggles and help them untangle their existing implementation of services.

**Comment by Neetuj** [comment]
Thanks .. will get a draft ready

**Comment by Neetuj** [comment]
https://app.xtensio.com/design/cdf8uvvd

**Comment by Neetuj** [comment]
**Cloud Architect Clay**

_Who_
Role:-  Enterprise architect responsible for technology selection, taking architectural decisions and trade offs and designing solutions 
Skills:- good domain knowledge since has been working in this domain for 10+ years

_What_
Goals:- Recommend latest and greatest tools, technologies that solves micro services related pain points
RTM:- conferences, Gartner, Market trends, Analysts/Consultants
Motivations:-interested in designing around microservices, how to mange them, track them and create reuse

_Why_
Frustrations/Blockers/Pain Points that keep them away from their Job to be done (JBTD):- ??

**Site reliability Engineer Shriya**
Who: 
Role:- responsible for maintaining the SLI creation, monitoring, alerting to meet SLOs 
Skills:- Good at operations, moved to SRE in 3 years back.  

What:
Goals:- have the right Automation in place to track and meet SLOs. 
RTM:- SRE conference , training, best practices articles and peer groups
Motivations:-are the ones that must answer the questions and need the visibility maps in order to make confident decisions about pushing a service to a cluster.

Why:
Frustrations/Blockers/Pain Points that keep them away from their Job to be done (JBTD):- ??

**DevOps engineers**
Who:
Role:-
Skills:-

What 
Goals:-
RTM:- 
Motivations:- 

Why:
Frustrations:- ??


**Microservices developer** 
Who:
Role:-
Skills:-

What 
Goals:-
RTM:- 
Motivations:- 

Why:
Frustrations:- ??

**Product Manager/Owner**
Who:
Role:-
Skills:-

What 
Goals:-
RTM:- 
Motivations:- 

Why:
Frustrations:- ??

**Comment by tlazebnyk** [comment]
**DevOps engineer Jake**

**Who**:
Role: 
- build and maintain the infrastructure and tools for continuous integration and delivery
- manage large scale software release deployments.

Skills:
- good knowledge of Unix/Linux based system and shell scripting
- familiarity with SOA, microservice, cloud native architecture and container-based solutions 
- good understanding of relational/NoSQL databases and programming languages

 
**What**
Goals:
- streamline versions control and monitoring
- improve repeatability of setup and code deployment

RTM: Conferences, trainings, technology review sessions with Senior Engineering Leadership
Motivations:
- interested in built-in continuous configuration versioning of all architecture components, e.g. microservices, web components, database updates,  environment variables
- Deployment to modern architecture or legacy environments
- deployment logs with critical release information about the end target locations

  
**Why**:
Frustrations:
- no traceability across the DevOps landscape
- no DevOps metrics


**Microservices developer Sam**
**Who**
Role: 
- create independent services that could work together with other services for larger application-wide functionality
- share microservices across teams and domains within the business
- support continuous delivery and failure isolation

Skills:
- Strong understanding of microservices architectures (leveraging APIs, containers and automation)
- Expert level programming skills
- Hands-on application troubleshooting and debugging skills 

 
**What**
Goals:
- reduce development time and make code/services more reusable
- get details on microservices mapping to applications where it’s used
- centralize microservices versions

RTM: Conferences, trainings, code reviews, technology review sessions with Senior Engineering Leadership
Motivations: 
- leverage domain structure for cataloging and sharing microservices which simplifies microservice reuse and sharing across development teams
- get track of microservice consumers through dependency map 

**Why**:
Frustrations:
- tracking changes requests, determining differences, tracking relationships and supporting users.
- Relatively complex deployment

**Comment by TracyRagan** [comment]
Ortelius Persona doc - https://docs.google.com/document/d/1Lt9bKz2fH_JH8iRVIpcaH_4aTxYqk8y8YmTfHn91AgU/edit?usp=drive_web

I created a Google Doc for this - Great job!  This gives us an amazing
start.

**Comment by Neetuj** [comment]
These have been added to the docs


 
DevOps engineer Jake
Who:
Role:
build and maintain the infrastructure and tools for continuous integration and delivery
manage large scale software release deployments.
Skills:
good knowledge of Unix/Linux based system and shell scripting
familiarity with SOA, microservice, cloud native architecture and container-based solutions
good understanding of relational/NoSQL databases and programming languages
What
Goals:
streamline versions control and monitoring
improve repeatability of setup and code deployment
RTM: Conferences, trainings, technology review sessions with Senior Engineering Leadership
Motivations:
interested in built-in continuous configuration versioning of all architecture components, e.g. microservices, web components, database updates, environment variables
Deployment to modern architecture or legacy environments
deployment logs with critical release information about the end target locations
Why:
Frustrations:
no traceability across the DevOps landscape
no DevOps metrics
 
 
 
 
 
 
Microservices developer Sam
Who
Role:
create independent services that could work together with other services for larger application-wide functionality
share microservices across teams and domains within the business
support continuous delivery and failure isolation
Skills:
Strong understanding of microservices architectures (leveraging APIs, containers and automation)
Expert level programming skills
Hands-on application troubleshooting and debugging skills
What
Goals:
reduce development time and make code/services more reusable
get details on microservices mapping to applications where it’s used
centralize microservices versions
RTM: Conferences, trainings, code reviews, technology review sessions with Senior Engineering Leadership
Motivations:
leverage domain structure for cataloging and sharing microservices which simplifies microservice reuse and sharing across development teams
get track of microservice consumers through dependency map
Why:
Frustrations:
tracking changes requests, determining differences, tracking relationships and supporting users.
Relatively complex deployment




Cloud Architect Clay
Who
Role:- 
Responsible for technology selection based on market insights and 
Responsible for taking architectural decisions and trade offs
Responsible for designing sustainable and compliant solutions
Responsible for vendor product/s analysis
Skills:-
Good domain knowledge since has been working in this domain for 10+ years
Good understanding of cloud, microservices, devops, SRE , API driven, TDD concepts. 
Good overall insights into the different systems involved and their interrelationships
What
Goals:- 
Recommend latest and greatest tools based on industry reports and technical analysis 
Design/recommend sound architecture to convert monolith to microservices which is, cloud friendly, is compliant, secure and supports agile development 
RTM:- 
Conferences, Gartner, Market trends, Analysts/Consultants
Motivations:-
Integrated solutions that e-use rather than reinvent  
Invested in helping the company adopt a microservices architecture to gain speed, agility while remaining secure and compliant. 
Why
Frustrations/Blockers/Pain Points :- 
How to avoid redundant microservices and promote re-usable microservices 
How to guide teams to transform monoliths into mocriservices while keeping the best practices in mind to avoid commonly known trends 
How to find the right solutions to help developers develop and maintain microservices that meet enterprise needs. 
 
 
 

Site Reliability Engineer Shriya
Who
Role:- 
Responsible for defining, maintaining, monitoring of SLO, SLIs of applications/microservices
Responsible for availability, latency, performance, efficiency, change management, monitoring, emergency response, and capacity planning of applications running in a cloud environment
Skills:-
Good knowledge of grafana, fortuna, prometheus , splunk 
Good knowledge of SRE concepts
good knowledge of Unix/Linux based system and shell scripting
What
Goals:- 
Ensure clear and correct  SLIs are defined for critical applications, microservices to meet the expected SLOs 
Ensure right graphs, dashboards are available to monitor health, performance, availability etc 
Ensure automated  alerting for problem space to the right team/people 
RTM:- 
Articles, conferences , trainings
Motivations:-
Maintaining smooth blameless culture with automated monitoring and actionable alerting of correct SLIs to maintain the expected SLOs. 
Why
Frustrations/Blockers/Pain Points :- 
Inability to tracking changes makes postmortems harder 
Finding time and resources to automate  the right SLI alerting , monitoring is hard
Avoiding alert fatigue is hard by avoiding false positives. 
 
 
 
Product Manager Pablo 
Role:- 
Responsible for clearly communicating business/user requirements and goals for the product/solution/feature/project being developed. 
Responsible for communicating roadmap, delivery timelines to various stakeholders and informing about  risks, changes in product scope/timeline
Responsible for setting reasonable SLOs with customers and pricing model that work for the company to make a business case for the new product/project/feature
 
Skills:-
Good knowledge of customer needs, expectations and motivations 
Good relationships with sales, marketing, vendors 
Good time, resource and stakeholder management skills. 
What
Goals:- 
Ensure the product/project/feature/solution/service meets the market-value fit and the company objective with his/her requirements and pricing and timing. 
Works with customers and engineers to agree to the required SLO
high quality products/services to solve customer pain points in time
Beating competition 
RTM:- 
Conferences, analysts, articles, demos, quarterly updates
Motivations:-
Testing Product hypothesis faster with the customers.creatively  
Tracking data that can help in validating product hypothesis 
Keeping SLO accurate (not unreasonable now unexpected) 
Keeping Tech Debt low  
Why
Frustrations/Blockers/Pain Points :- 
Inability to track hypothesis due to high risks or lack of data or lack of deployment strategies 
Slow and error prone SDLC which is harder to track and fix






Others remaining:- 

Auditor Arya 
Who:
Role:-
Skills:-

What
Goals:-
RTM:-
Motivations:-

Why:
Frustrations:- ??

**Comment by tlazebnyk** [comment]
Added to doc one more persona - QA Engineer Maria.
Planning to add tomorrow:

- Delivery Manager Alex (FinTech) 

- Business Development Manager Tom (IBM/VMWare)

**Comment by tlazebnyk** [comment]
> Added to doc one more persona - QA Engineer Maria.
> Planning to add tomorrow:
> 
> * Delivery Manager Katie (FinTech)
> * Business Development Manager Tom (IBM/VMWare)

Updated Google document. Please let me know your thoughts. Thank you.

**Comment by sbtaylor15** [comment]
@tlazebnyk join the [Ortelius Google Group](https://groups.google.com/g/ortelius-dev) so you can have access to the Google Docs, Calendar etc.

**Comment by tlazebnyk** [comment]
> @tlazebnyk join the [Ortelius Google Group](https://groups.google.com/g/ortelius-dev) so you can have access to the Google Docs, Calendar etc.

Thank you. Requested access as needed.

**Comment by Neetuj** [comment]
@tlazebnyk 
I am unable to access google docs at office :) so will add more on that later. 
Also I feel that since google doc is not accessible to everybody we should also add our personas here in comments ( so that others who might be interested in similar personas can refer to them and may be even help us improve/refine these personas) 

@sbtaylor15  @TracyRagan any concerns on adding personas  here as well on github apart from adding it to the google doc (which everybody might not have access). 

For next steps I am thinking 
1) "prioritize" certain personas for Ortelius
2) validate them with real users and do a need analysis of these personas with Ortelius in mind. (some work has been done in that direction so merge with that work)

**Comment by TracyRagan** [comment]
@Neetuj  and @tlazebnyk  no problem with adding personas here.

**Comment by tlazebnyk** [comment]
@TracyRagan and @Neetuj Adding personas details below (including IT Executive and Security Engineer added during community session on Monday 11/23):

1. 

### **DevOps engineer Jake**
**Who:**
_Role:_
- build and maintain the infrastructure and tools for continuous integration and delivery
- manage large scale software release deployments.

Skills:
- good knowledge of Unix/Linux based system and shell scripting
- familiarity with SOA, microservice, cloud native architecture and container-based solutions
- good understanding of relational/NoSQL databases and programming languages

**What**
Goals:

- streamline versions control and monitoring
- improve repeatability of setup and code deployment
- maintain clear step-by-step release deployment instructions

RTM: Conferences, trainings, technology review sessions with Senior Engineering Leadership

Motivations:

- interested in built-in continuous configuration versioning of all architecture components, e.g. microservices, web components, database updates, environment variables
- deployment to modern architecture or legacy environments
- deployment logs with critical release information about the end target locations
- Keep track of microservice versions configurations released to production (and latest versions states on lower environments)

**Why:**
Frustrations:

- no traceability across the DevOps landscape
- no DevOps metrics


2. 
### **Microservices developer Sam**
**Who**
Role:

- create independent services that could work together with other services for larger application-wide functionality
- share microservices across teams and domains within the business
- support continuous delivery and failure isolation

Skills:

- Strong understanding of microservices architectures (leveraging APIs, containers and automation)
- Expert level programming skills
- Hands-on application troubleshooting and debugging skills

**What**
Goals:

- reduce development time and make code/services more reusable
- get details on microservices mapping to applications where it’s used
- centralize microservices versions

RTM: Conferences, trainings, code reviews, technology review sessions with Senior Engineering Leadership

Motivations:

- leverage domain structure for cataloging and sharing microservices which simplifies microservice reuse and sharing across development teams
- get track of microservice consumers through dependency map

**Why:**
Frustrations:

- tracking changes requests, determining differences, tracking relationships and supporting users.
- Relatively complex deployment

3.
### **Cloud Architect Clay**
**Who**
Role:- 

- Responsible for technology selection based on market insights and 
- Responsible for taking architectural decisions and trade offs
- Responsible for designing sustainable and compliant solutions
- Responsible for vendor product/s analysis

Skills:-

- Good domain knowledge since has been working in this domain for 10+ years
- Good understanding of cloud, microservices, devops, SRE , API driven, TDD concepts. 
- Good overall insights into the different systems involved and their interrelationships

**What**
Goals:- 

- Recommend latest and greatest tools based on industry reports and technical analysis 
- Design/recommend sound architecture to convert monolith to microservices which is, cloud friendly, is compliant, secure and supports agile development 

RTM:- Conferences, Gartner, Market trends, Analysts/Consultants

Motivations:-

- Integrated solutions that e-use rather than reinvent  
- Invested in helping the company adopt a microservices architecture to gain speed, agility while remaining secure and compliant. 

**Why**
Frustrations/Blockers/Pain Points :- 

- How to avoid redundant microservices and promote re-usable microservices 
- How to guide teams to transform monoliths into mocriservices while keeping the best practices in mind to avoid commonly known trends 
- How to find the right solutions to help developers develop and maintain microservices that meet enterprise needs. 

 

4.
Site Reliability Engineer Shriya
Who
Role:- 

- Responsible for defining, maintaining, monitoring of SLO, SLIs of applications/microservices
- Responsible for availability, latency, performance, efficiency, change management, monitoring, emergency response, and capacity planning of applications running in a cloud environment

Skills:-

- Good knowledge of grafana, fortuna, prometheus , splunk 
- Good knowledge of SRE concepts
- good knowledge of Unix/Linux based system and shell scripting

**What**
Goals:- 

- Ensure clear and correct  SLIs are defined for critical applications, microservices to meet the expected SLOs 
- Ensure right graphs, dashboards are available to monitor health, performance, availability etc 
- Ensure automated  alerting for problem space to the right team/people 

RTM:- Articles, conferences , trainings

Motivations:-

- Maintaining smooth blameless culture with automated monitoring and actionable alerting of correct SLIs to maintain the expected SLOs. 

**Why**
Frustrations/Blockers/Pain Points :- 

- Inability to tracking changes makes postmortems harder 
- Finding time and resources to automate  the right SLI alerting , monitoring is hard
- Avoiding alert fatigue is hard by avoiding false positives. 

 
5.
### **Product Manager Pablo** 
**Who**
Role:- 

- Responsible for clearly communicating business/user requirements and goals for the product/solution/feature/project being developed. 
- Responsible for communicating roadmap, delivery timelines to various stakeholders and informing about  risks, changes in product scope/timeline
- Responsible for setting reasonable SLOs with customers and pricing model that work for the company to make a business case for the new product/project/feature

 
Skills:-

- Good knowledge of customer needs, expectations and motivations 
- Good relationships with sales, marketing, vendors 
- Good time, resource and stakeholder management skills. 

**What**
Goals:- 

- Ensure the product/project/feature/solution/service meets the market-value fit and the company objective with his/her requirements and pricing and timing. 
- Works with customers and engineers to agree to the required SLO
- high quality products/services to solve customer pain points in time
- Beating competition 

RTM:- Conferences, analysts, articles, demos, quarterly updates

Motivations:-

- Testing Product hypothesis faster with the customers.creatively  
- Tracking data that can help in validating product hypothesis 
- Keeping SLO accurate (not unreasonable now unexpected) 
- Keeping Tech Debt low  

**Why**
Frustrations/Blockers/Pain Points :- 

- Inability to track hypothesis due to high risks or lack of data or lack of deployment strategies 
- Slow and error prone SDLC which is harder to track and fix

6.
### **QA Engineer Maria**
**Who**
Role:- 

- Create and maintain Quality Assurance Plans: exercise judgement in selecting methods, techniques and evaluation criteria for obtaining results
- Execute tests following QA Plans: individual features testing, integration and components testing, performance testing, regression and UAT  
- Create automated tests  

Skills:-

- Hands on experience in manual and automated software testing
- Good understanding of testing techniques and strategies
- Ability to work on complex issues where analysis of situations or data requires an in-depth evaluation of variable factors - debugging & troubleshooting
- Knowledge of microservices and cloud native architectures

**What**
Goals:-

- Identify set of tests to be executed: clearly define all applications where one or another microservice is used
- Continuously increase test coverage by automated tests and reducing manual testing work

 
RTM:- 
Conferences, team knowledge share/code reviews, articles, demos, quarterly updates

Motivations:-

- Leveraging Dependency maps to easily access details on logical dependencies within application and specifically details about microservices which are consumed
- Integration with CD pipeline and continuous versioning of microservice configurations prior to release at any state (Dev,Test, Prod)

**Why**
Frustrations/Blockers/Pain Points :- 

- Managing dependent components when testing microservices in a cost and time effective way
- Coordination between several testing teams and deployments of correct microservice versions and applications versions which consume microservices for testing

7.
### **Delivery Manager Katie (FinTech)**
**Who**
Role:- 

- Responsible for end-to-end delivery of the project
- Release Management – ensuring that project schedules and priorities are aligned across all cross-functional teams
- Identifying and implementing best practices from both process and technical perspectives
- Presenting regular (weekly, monthly, quarterly) reports to key stakeholders and management, reflecting team progress against targeted KPIs

Skills:-

- A strong technical background, could include experience in solution architecture and database design
- Good FinTech domain knowledge
- Excellent communication, presentation and facilitation skills 

**What**
Goals:-

- Ensuring the team's processes and tasks are carried out efficiently, all dependencies are outlined and projected on the delivery timeline
- Making sure deliverables are compliant with audit requirements 
- Determining ways to reduce costs without sacrificing end users satisfaction

RTM:- 
Conferences,workshops, articles, internal company updates

Motivations:-

- Adopting Domain structure for cataloging and sharing microservices which amplifies migration to microservices architecture  
- Leveraging Dependency maps to easily access details on logical dependencies within application and specifically details about microservices which are consumed

**Why**
Frustrations/Blockers/Pain Points :- 

- Complexity of support and new features development within legacy systems 
- Alignment with specific technical audit requirements within FinTech industry and continuous provision of regulatory compliance reports to key stakeholders

8.
### **Business Development Manager Tom (IBM/VMWare)**
**Who**
Role:- 

- Build positive and productive working relationships with customers for business growth
- Develop new business opportunities, effective sales plans and business cases to meet and/or exceed sales objectives
- Analyze competitive landscape
- Provide prospect reporting and status updates to key stakeholders.


Skills:-

- In-depth knowledge of business products and value proposition
- A strong technical background, could include prior experience working as product manager, software engineer, QA engineer etc.
- Experience with design and implementation of business development strategy
- Excellent communication, presentation and facilitation skills 

**What**
Goals:-

- Win new clients through:
-- delivery of better scalable product solutions among competitors
-- provision of customizations (as needed) and/or packaging services 

RTM:- 
Conferences,workshops, articles, internal company updates

Motivations:-

- Adopting Domain structure for cataloging and sharing microservices which amplifies migration to microservices architecture  
- Leveraging Dependency maps to easily access details on logical dependencies within application and specifically details about microservices which are consumed

**Why**
Frustrations/Blockers/Pain Points :- 

- Features scaling and complexity of customization when it comes to quite specific client requirements which cannot be handled through standard offering


9.
### **IT Executive Chris (FinTech)**
**Who**
Role:- 

- Overseeing specific technology functions across company departments
- Determining IT budget, software and hardware, equipment needs
- Contributing to the overall business strategy and making sure it is aligned with company level business goals
- Staying up-to-date with emerging technologies and identifying opportunities for innovation, cost savings, etc.


Skills:-

- In-depth knowledge of the industry, business products and competitive landscape
- A strong technical background and B.S. in Computer Information Systems/MBA in Executive Management
- 15+ years of experience leading teams and overseeing technology operations
- Excellent communication, presentation and facilitation skills 

**What**
Goals:-

- Drive FinTech business growth and scaling through introduction of new technologies which would handle best business needs
- Cost saving through series of technology upgrades and operational changes

RTM:- 
Technology communities updates, conferences,workshops, articles, internal company updates

Motivations:-

- Adopting Domain structure for cataloging and sharing microservices which amplifies migration to microservices architecture  
- Leveraging Dependency maps to easily access details on logical dependencies within application and specifically details about microservices which are consumed
- Integrate Ortelius into CD pipeline to continuously version microservice configurations prior to release at any state (Dev,Test, Prod) 

**Why**
Frustrations/Blockers/Pain Points :- 

- Features scaling and complexity of customization when it comes to quite specific client requirements which cannot be handled through standard offering

10.
### **Security Engineer Brinda**
**Who**
Role:- 

- Develops, executes and tracks the performance of security measures to protect information and network infrastructure 
- Identifies, defines and documents system security requirements and recommends solutions to management
- Configures, troubleshoots and maintains security infrastructure software and hardware
- Installs software that monitors systems and networks for security breaches and intrusions
- Plans, implements and updates company's information security strategy
- Educates and trains staff on information system security best practices


Skills:-

- BS in Computer Science and 5+ years of hands-on experience working as System Security Engineer
- Extensive knowledge of operating systems and database security
- Proficiency in networking technologies, network security and network monitoring solutions
- In-depth knowledge of security protocols and principles
- Critical thinking skills and ability to solve complex problems

**What**
Goals:-

- create new ways to solve existing production security issues 
- recommending security enhancements to management
- developing automated scripts to handle and track incidents, continuously watching out for irregular system behaviour 
- supervising changes in software and hardware, leading breaches analysis

RTM:- 
Conferences,workshops, articles, internal company updates

Motivations:-

- Adopt Ortelius microservices deployment and record critical release information about the end target locations to make data-driven decisions when something goes wrong.
- With help of Ortelius support continuous configuration versioning of microservices , web components, database updates, environment variables, application binaries and infrastructure components
- Leveraging Ortelius’ engine for pushing changes using an agentless architecture. 


**Why**
Frustrations/Blockers/Pain Points :- 

- Execute and track the performance of security measures to protect information, network infrastructure and system overall

**Comment by Neetuj** [comment]
@tlazebnyk  do we have visuals for these personas too?

**Comment by tlazebnyk** [comment]
@Neetuj no, not yet, I will create them by the end of this week
