### ISSUE TITLE
Blog 1 - Ortelius Contributor Content

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#191]
We need to add content for the " Ortelius contributor content" blog category.  Please create your blog in Google docs under the /blog directory.  https://ortelius.io/category/ortelius-contributors/

**Comment by TracyRagan** [comment]
Any subject around CD Trends, K8s, microservices, service mesh you feel passionate about.

**Comment by Neetuj** [comment]
_Ok copying the GSOC bog content here for now (since I can't access google drive)_ 



**Announcing Ortelius Entry to GSOC( Google Summer Of Code)**
We are excited to announce that this year will be Ortelius’s first entry (through CD Foundation) at Google Summer Of Code (GSOC )and we are looking forward to welcoming some new students to this community through GSOC. 
We have carefully chosen 3 projects and 5 mentors to make this program a success. 
For those of you who are new to GSOC, It’s a paid summer internship where students apply to work on an open source projects in during their summer break and the f/oss project community provides them mentor/s to ensure the students have a great learning experience. The open source community proposes the projects they will like some help with and the students submit a project plan to tackle those projects. Mentor and students maintain a periodic cadence to make sure students have a productive and learning internship. 

I have personally mentored twice for GSOC through ABI’s Systers program when I was a software engineer and have found some delightful mentorships. The students not only learned the technical skills to contribute to an open source and sharpen their programming skills but they also learn a lot of soft skills. My students learned to work with other team members, provide updates in timely manner and resolve dependencies and sometimes even conflicts (especially when there were cross-coupling projects). Overall I think it is an excellent hands-on experience for students to get a glimpse of their work-life could be after they graduate. I wish I had this option when I was doing my Bachelors and Masters 😊 

For those of you who are new Ortelius community, we are very supportive and engaged opensource community with members from all over the world (add how many members). Ortelius is a microservice management platform that versions and tracks microservices, their consuming applications, ownership, blast radius and where they have been deployed with all critical deployment metadata. By centralizing and tracking detailed configuration data, Ortelius provides you a proactive view of how your microservice architecture is changing overtime. 
For GSOC projects we have selected these 3 enhancements to Ortelius and we look forward to the applications students will submit to close these projects successfully. 
https://github.com/ortelius/ortelius/issues?q=is%3Aissue+is%3Aopen+label%3Agsoc

Students, here is a workflow of how it works and what to expect  :- 
1)	Checkout https://ortelius.io/ to understand what the opensource project is about. 
2)	Checkout the 3 issues we have created to enter into GSOC https://github.com/ortelius/ortelius/issues?q=is%3Aissue+is%3Aopen+label%3Agsoc
3)	March 9th to April 12th 2021 Reach out to us if you are interested in discussing these projects https://ortelius.io/expert/
4)	March 29-April 13 2021 register and submit applications to Ortellius with a proposal to work on the issue of your choice from above 3 issues 
5)	April13-May 17 2021 we will review and select student proposals
6)	May 17-June 7 2021Once you get selected we will pair you with mentor/s to work with you an create a project plan 
7)	June 7 to August 31 2021 you will execute on the project plan to close the issue assigned to you and reach out to your mentor and community if you hit any blockers. Mentors and Students will submit evaluations of each other twice in this period and at the end based on the code submission, project summary and evaluations GSOC assigns Pass/Fail statuses.

**Comment by Neetuj** [comment]
@sbtaylor15  please let me know if we should go deeper into the 3 issues that are identified for GSOC .. (why we chose them .. why they should be good for a 2 month project for a new student .. what all they will learn (apart from soft skills) ??

**Comment by Neetuj** [comment]
Uploaded a copy in the blog folder as well
