### ISSUE TITLE
Assign permission to devops aks cluster to postgres disk

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#388]
The deployment for the Ortelius console app into the cluster with ArgoCD has a deployment that references a subscription that I dont have access to.  

It is referenced here: https://github.com/ortelius/ortelius/blob/main/chart/ortelius-console/values.yaml

Managed Identity: https://portal.azure.com/#@stevedeployhub.onmicrosoft.com/resource/subscriptions/57b482cf-3355-4f0c-8adb-6d6bbb1b2cf7/resourceGroups/devops-usea-prod-node/providers/Microsoft.ManagedIdentity/userAssignedIdentities/devops-usea-prod-agentpool/overview

I need that the managed identity has read access to this disk which needs to be configured in azure.

Error: 
Events:
  Type     Reason              Age                       From                     Message
  ----     ------              ----                      ----                     -------
  Warning  FailedMount         20m (x1542 over 11d)      kubelet                  Unable to attach or mount volumes: unmounted volumes=[postgres], unattached volumes=[default-token-7tf9t pos
tgres]: timed out waiting for the condition
  Warning  FailedMount         4m6s (x5822 over 11d)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[postgres], unattached volumes=[postgres default-token-
7tf9t]: timed out waiting for the condition
  Warning  FailedAttachVolume  3m12s (x1905 over 2d16h)  attachdetach-controller  AttachVolume.Attach failed for volume "postgres" : Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, Ra
wError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: {"error":{"code":"AuthorizationFailed","message":"The client 'ab775263-961f-43be-8d1e-f0f374062106' with object id 'a
b775263-961f-43be-8d1e-f0f374062106' does not have authorization to perform action 'Microsoft.Compute/disks/read' over scope '/subscriptions/57b482cf-3355-4f0c-8adb-6d6bbb1b2cf7/resourceGrou
ps/MC_ortelius_aks-cluster_eastus/providers/Microsoft.Compute/disks/postgresDisk' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
ortelius@devops-usea-prod:~/ortelius-kubernetes/kube-infra$

**Comment by sbtaylor15** [comment]
@bradmccoydev skip that chart.  Use the following charts to install.  These use the managed postgres db instead of a volume mount.

### Charts locations:

- [ortelius](https://github.com/ortelius/ortelius/tree/svc_cat) **svc_cat** branch
  - chart/ms-general
  - chart/ms-ui
  - chart/ms-nginx
- [ortelius-ms-dep-pkg-cud](https://github.com/ortelius/ortelius-ms-dep-pkg-cud/tree/deploy) **deploy** branch
   - chart/ms-dep-pkg-cud
- [ortelius-ms-dep-pkg-r](https://github.com/ortelius/ortelius-ms-dep-pkg-r/tree/deploy)  **deploy** branch
   - chart/ms-dep-pkg-r
- [ortelius-ms-textfile-crud](https://github.com/ortelius/ortelius-ms-textfile-crud/tree/deploy)  **deploy** branch
   -   chart/ms-textfile-crud
- [ortelius-ms-compitem-crud](https://github.com/ortelius/ortelius-ms-compitem-crud/tree/deploy)  **deploy** branch
   - chart/ms-compitem-crud
- [ortelius-ms-validate-user](https://github.com/ortelius/ortelius-ms-validate-user/tree/deploy)  **deploy** branch
   - chart/ms-validate-user

**Comment by sachajw** [comment]
@sbtaylor15 & @bradmccoydev do you mean adapt the above examples for the console chart in order to not use a volume mount and use the dedicated Postgres instance running in Azure?

**Comment by sbtaylor15** [comment]
@sachajw and @bradmccoydev the console chart is the monolith image.  That is being replaced by the other charts.  So no need to deploy the console one.
